//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductGroup.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect
    {
        public int Id { get; set; }
        public string TaskId { get; set; }
        public string WWId { get; set; }
        public string WWIdImg { get; set; }
        public string TransferAccountsImg { get; set; }
        public string CityPartner { get; set; }
        public string Clerk { get; set; }
        public string Remarks { get; set; }
        public string ShopName { get; set; }
        public Nullable<decimal> TaskPrice { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public string OrderImg1 { get; set; }
        public string OrderImg2 { get; set; }
        public string OrderImg3 { get; set; }
        public string OrderImg4 { get; set; }
        public Nullable<int> LastCollect { get; set; }
    }
}
